name: CLA Assistant

on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - closed
      - synchronize

jobs:
  add-cla-comment:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
      statuses: write
    steps:
      - name: Add CLA Comment
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_TOKEN }}
        with:
          path-to-document: https://github.com/loopholelabs/contributor-signatures/blob/main/CLA.md
          allowlist: bot*
          branch: v1-signatures
          path-to-signatures: v1-cla.json
          remote-organization-name: loopholelabs
          remote-repository-name: contributor-signatures
          lock-pullrequest-aftermerge: true
